conn = mysql.connector.connect(
    host=st.secrets["mysql"]["localhost"],
    user=st.secrets["mysql"]["root"],
    password=st.secrets["mysql"]["12345"],
    database=st.secrets["mysql"]["DAILY_SCHEDULE_AND_DRIVER_DATA"]
)

